name: Rust Bindings

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ndoe_bindgen
      run: cargo install nj-cli
    - name: Build
      run: nj-cli build --verbose --release
    - name: Run tests
      run: node ./examples/simple.js
